.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SPICEC 1 "November 29, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
spicec \- Spice client
.SH SYNOPSIS
.B spicec
.RI [ \-h,\ \-\-host\ <host> ] 
.RI [\-p,\ \-\-port\ <port> ] 
.RI [ \-s,\ \-\-secure\-port\ <port> ] 
.RI [ \-\-secure\-channels\ <ch0,\ ch1...> ] 
.RI [ \-\-unsecure\-channels\ <ch0,\ ch1...> ] 
.RI [ \-w,\ \-\-password\ <password> ] 
.RI [ \-f,\ \-\-full\-screen[\=auto\-conf] ] 
.RI [ \-\-canvas\-type\ <type1,\ type2...> ] 
.RI [ \-\-enable\-channels\ <ch0,\ ch1...> ] 
.RI [ \-\-disable\-channels\ <ch0,\ ch1...> ] 
.RI [ \-\-help ] 
.SH DESCRIPTION
spicec is a Spice client, it can be used to connect to Spice server, such as spice compatible QEMU
.SH OPTIONS
.TP
.B \-h,\ \-\-host\ <host>
Spice server address. 
.TP
.B \-p,\ \-\-port\ <port> 
Spice server port 
.TP
.B \-s,\ \-\-secure\-port\ <port> 
Spice server secure port
.TP
.B \-\-secure\-channels\ <ch0,\ ch1...> 
Force secure connection on the specified channels
Channels are: main, display, inputs, cursor, playback and record
By default, any channel can be secured, depending on the \-\-secure-port availability.
.TP
.B \-\-unsecure\-channels\ <ch0,\ ch1...>
Force unsecure connection on the specified channels
Channels are: main, display, inputs, cursor, playback and record.
By default, any channel can be unsecured, depending on the \-\-port availability.
.TP
.B \-w,\ \-\-password\ <password> 
Set a ticketing password (default is none)
.TP
.B \-s,\ \-\-secure\-port\ <port> 
Spice server secure port
.TP
.B \-f,\ \-\-full\-screen[\=auto\-conf]
Open in a full screen mode. Optional automatic configuration of the remote display settings
according to the client display settings. A guest agent must be installed and started for this
option.
.TP
.B \-\-canvas\-type\ <type1,\ type2...> 
Select the available renderer. The order determines precedence
For Linux client : only “cairo” canvas type is available.
For Windows client : available types are “gdi” and “cairo”. The default is “gdi”.
.TP
.B \-\-enable\-channels\ <ch0,\ ch1...> 
Enable the specified channels. Use “all” for enabling all possible channels. Use the
following names for enabling only the selected channels: “display”, “inputs”, “cursor”,
“playback” and “record”. By default all channels are enabled.
.TP
.B \-\-disable\-channels\ <ch0,\ ch1...>
Disable the specified channels. Use “all” for disabling all possible channels. Use the
following names for enabling only the selected channels: “display”, “inputs”, “cursor”,
“playback” and “record.” By default all channels are enabled.
.TP
.B \-\-help
Show command help.
.SH CONTROL HOT KEYS
.B Shift \+ F11
Toggle full-screen / window mode
.TP
.B Shift \+ F12
Release the cursor if captured in window
.TP
On debug mode, these are available as well:
.TP
.B Shift \+ F5
Connect to the server
.TP
.B Shift \+ F6
Disconnect from the server

.SH SEE ALSO
Spice related documents can be found at http://www.spice-space.org/documentation.html
.SH AUTHOR
Spice project
.PP
This manual page was written by Liang Guo <bluestonechina@gmail.com>, for the Debian project (and may be used by others). Permission is  granted to  copy, distribute and/or modify this document under the terms of the Creative Commons Attribution-Share Alike 3.0 United States License. (See http://creativecommons.org/licenses/by-sa/3.0/us/legalcode)
.
